services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: stream-ai-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stream-ai-dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: stream-ai-redis
    ports:
      - '6379:6379'
    restart: unless-stopped

volumes:
  pgdata:
